In [1]:
import sys
sys.path.insert(0,"../")

In [2]:
from utils.dataloader import CustomImageDataset
from utils.transformations import CustomTransformations
from models.resnet50 import MyopiaClasificationModel
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks.progress import TQDMProgressBar

In [38]:
from utils.createCSV import createCSV

In [40]:
createCSV("../../test/","../output.csv")

In [3]:
# path donde está el modelo resnet con los pesos
!cp /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth .

In [3]:
import torch
from torch.utils.data import DataLoader
train_features = CustomImageDataset("../output.csv","../../test/",transform=CustomTransformations(512))
train_loader = DataLoader(train_features,batch_size=2,shuffle=True,num_workers=3)

# Initialize a trainer
trainer = Trainer(
    accelerator="auto",
    devices=1 if torch.cuda.is_available() else None,  # limiting got iPython runs
    max_epochs=7,
    callbacks=[TQDMProgressBar()],
    log_every_n_steps=4
)

miopia_model = MyopiaClasificationModel(512)

# Train the model ⚡


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [4]:
trainer.fit(miopia_model, train_loader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params
-------------------------------------
0 | model | ResNet50TF | 23.5 M
-------------------------------------
23.5 M    Trainable params
0         Non-trainable params
23.5 M    Total params
94.057    Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

`Trainer.fit` stopped: `max_epochs=7` reached.


In [17]:
from torchvision.io import read_image
from torchvision.io import ImageReadMode

In [29]:
img = read_image("../../test/H0001.jpg").type_as(torch.FloatTensor())

In [30]:
img = transforms.Resize((512,512))(img)

In [5]:
x =torch.rand(1,3)

In [6]:
x

tensor([[0.3252, 0.8729, 0.4292]])

In [8]:
from torch.nn import functional as F

In [20]:
yhat = F.softmax(x,dim=1)

In [22]:
label = torch.tensor([2])
label = F.one_hot(label, 3).float()

In [23]:
label

tensor([[0., 0., 1.]])

In [24]:
F.cross_entropy(yhat,label)

tensor(1.1465)

In [32]:
img2 = torch.nn.Conv2d(3,3, (3,3), stride=1, padding=1)(img)

In [33]:
img2.shape

torch.Size([3, 512, 512])

In [5]:
(1024-3)/2 +1

511.5

In [15]:

(512-3 + 1 )/2 + 1 

256.0

In [ ]:
.fc = nn.Linear(512, 1)

In [18]:
num_classes = 2  # 1 class (person) + background

print(model.fc)
# 1024

Linear(in_features=2048, out_features=1000, bias=True)


In [36]:
model.fc = nn.Linear(2048,3,bias=True)

In [37]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [34]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)

In [35]:
output

tensor([[0.7326, 0.1827, 0.0847],
        [0.1458, 0.1674, 0.6867]])