In [11]:
from utils.dataloader_dali import SimpleDALIGenericIterator
import pandas as pd

In [12]:
    train_pipe = SimpleDALIGenericIterator("../test", 6, 0)
    train_pipe.build() #Se construye el pipeline
    
    for i in range(10): #bucle de 10 iteraciones, para obtener una tanda de datos de 6 imágenes
        data = train_pipe.run() #contiene los tenserores DALI con las imágenes decodificadas.
        print(data)
        images = data[0].as_cpu().as_array() #se accede primera entra de la lista y se convierte en una matriz numpy

TypeError: define_graph() takes 0 positional arguments but 1 was given

In [40]:
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

image_dir = "../test/"
max_batch_size = 2


@pipeline_def
def simple_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir,device='gpu')
    images = fn.decoders.image(jpegs)

    return images, labels



In [41]:
pipe = simple_pipeline(batch_size=2, num_threads=1, device_id=0)

In [42]:
pipe.build()

RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers__File encountered:
[/opt/dali/dali/pipeline/operator/operator_factory.h:54] Assert on "creator_it != registry_.end()" failed: Operator "readers__File" not registered for gpu.
Stacktrace (83 entries):
[frame 0]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/libdali.so(+0x847ff) [0x7fa1ed0c87ff]
[frame 1]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/libdali.so(+0x15dc5d) [0x7fa1ed1a1c5d]
[frame 2]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/libdali.so(dali::InstantiateOperator(dali::OpSpec const&)+0x264) [0x7fa1ed19f114]
[frame 3]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/libdali.so(dali::OpGraph::InstantiateOperators()+0x8e) [0x7fa1ed15586e]
[frame 4]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<dali::PipelineOutputDesc, std::allocator<dali::PipelineOutputDesc> >)+0x7ec) [0x7fa1ed1bbc2c]
[frame 5]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0x5d0f2) [0x7fa1d98080f2]
[frame 6]: /usr/local/lib/python3.8/dist-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0xa5f05) [0x7fa1d9850f05]
[frame 7]: /usr/bin/python(PyCFunction_Call+0x59) [0x5f6929]
[frame 8]: /usr/bin/python(_PyObject_MakeTpCall+0x296) [0x5f74f6]
[frame 9]: /usr/bin/python() [0x50c383]
[frame 10]: /usr/bin/python(_PyEval_EvalFrameDefault+0x5786) [0x570b26]
[frame 11]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 12]: /usr/bin/python(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 13]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 14]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 15]: /usr/bin/python(PyEval_EvalCode+0x27) [0x6902a7]
[frame 16]: /usr/bin/python() [0x6023c4]
[frame 17]: /usr/bin/python() [0x5c6730]
[frame 18]: /usr/bin/python(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 19]: /usr/bin/python() [0x501488]
[frame 20]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 21]: /usr/bin/python() [0x501488]
[frame 22]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 23]: /usr/bin/python() [0x501488]
[frame 24]: /usr/bin/python() [0x505166]
[frame 25]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 26]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 27]: /usr/bin/python(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 28]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 29]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 30]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 31]: /usr/bin/python(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 32]: /usr/bin/python() [0x50bc2c]
[frame 33]: /usr/bin/python(PyObject_Call+0x62) [0x5f6082]
[frame 34]: /usr/bin/python(_PyEval_EvalFrameDefault+0x1f35) [0x56d2d5]
[frame 35]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 36]: /usr/bin/python() [0x50bca0]
[frame 37]: /usr/bin/python(_PyEval_EvalFrameDefault+0x187f) [0x56cc1f]
[frame 38]: /usr/bin/python() [0x501488]
[frame 39]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 40]: /usr/bin/python() [0x501488]
[frame 41]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 42]: /usr/bin/python() [0x501488]
[frame 43]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 44]: /usr/bin/python() [0x501488]
[frame 45]: /usr/bin/python(_PyEval_EvalFrameDefault+0x2136) [0x56d4d6]
[frame 46]: /usr/bin/python() [0x501488]
[frame 47]: /usr/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so(+0x7ef9) [0x7fa2011a9ef9]
[frame 48]: /usr/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so(+0x9083) [0x7fa2011ab083]
[frame 49]: /usr/bin/python(_PyObject_MakeTpCall+0x296) [0x5f74f6]
[frame 50]: /usr/bin/python() [0x600f63]
[frame 51]: /usr/bin/python() [0x5c6617]
[frame 52]: /usr/bin/python(PyVectorcall_Call+0x58) [0x5f6648]
[frame 53]: /usr/bin/python(_PyEval_EvalFrameDefault+0x691b) [0x571cbb]
[frame 54]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 55]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 56]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 57]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 58]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 59]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 60]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 61]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 62]: /usr/bin/python(_PyFunction_Vectorcall+0x1b6) [0x5f6cd6]
[frame 63]: /usr/bin/python(_PyEval_EvalFrameDefault+0x85a) [0x56bbfa]
[frame 64]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 65]: /usr/bin/python() [0x50bca0]
[frame 66]: /usr/bin/python(_PyEval_EvalFrameDefault+0x5786) [0x570b26]
[frame 67]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 68]: /usr/bin/python(PyEval_EvalCode+0x27) [0x6902a7]
[frame 69]: /usr/bin/python() [0x6023c4]
[frame 70]: /usr/bin/python() [0x5c6730]
[frame 71]: /usr/bin/python(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 72]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 73]: /usr/bin/python(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 74]: /usr/bin/python(_PyEval_EvalFrameDefault+0x72d) [0x56bacd]
[frame 75]: /usr/bin/python(_PyEval_EvalCodeWithName+0x26a) [0x569dba]
[frame 76]: /usr/bin/python(_PyFunction_Vectorcall+0x393) [0x5f6eb3]
[frame 77]: /usr/bin/python(PyObject_Call+0x62) [0x5f6082]
[frame 78]: /usr/bin/python() [0x6b9a92]
[frame 79]: /usr/bin/python(Py_RunMain+0x379) [0x6b9e99]
[frame 80]: /usr/bin/python(Py_BytesMain+0x2d) [0x6ba0bd]
[frame 81]: /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fa20381a083]
[frame 82]: /usr/bin/python(_start+0x2e) [0x5fc5fe]

Current pipeline object is no longer valid.

In [39]:
pipe_out = pipe.run()
print(pipe_out)

(TensorListCPU(
    [[[[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      ...

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]]


     [[[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      ...

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       ...
       [0 0 0]
       [0 0 0]]]],
    dtype=DALIDataType.UINT8,
    layout="HWC",
    num_samples=2,
    shape=[(1444, 1444, 3), (1444, 1444, 3)]), TensorListCPU(
    [[0]
     [0]],
    dtype=DALIDataType.INT32,
    num_samples=2,
    shape=[(1,), (1,)]))
